Mc logging
ONSdigital/es-aggregation-sg pull request #85
Opened 2020-12-22 12:59 UTC by glanvl

Spp-logging module added.
Plus alphabetising.

2020-12-22 13:34 UTC, Piwington requested changes
The Alphabet

2020-12-22 13:34 UTC, Piwington commented on aggregation_top2_wrangler.py
> +                "top2_column": top2_column
Top before Total

2020-12-22 13:34 UTC, Piwington commented on combiner.py
>          in_file_name = runtime_variables["in_file_name"]
Two lots of in_file_name?

2020-12-22 13:34 UTC, Piwington commented on dev-requirements.txt
> +# Force build
I assume this was for an image build. Should go before merge.

2020-12-22 13:34 UTC, Piwington commented on tests/test_aggregation.py
> +        "additional_aggregated_column": "strata",
Alphabetical

2020-12-22 13:34 UTC, Piwington commented on tests/test_aggregation.py
>          "aggregated_column": "region",
B after A

2020-12-22 13:34 UTC, Piwington commented on tests/test_aggregation.py
>              "in_file_name": "test_wrangler_splitter_input",
_ before  letters.

2020-12-22 13:34 UTC, Piwington commented on aggregation_bricks_splitter_wrangler.py
>                  "region_column": region_column,
_ before letters.

2020-12-22 16:48 UTC, glanvl commented on tests/test_aggregation.py
>              "in_file_name": "test_wrangler_splitter_input",
Are you sure?

2020-12-23 09:04 UTC, rhodriguerrier approved these changes

2020-12-23 09:50 UTC, Piwington approved these changes

2020-12-23 10:21 UTC, merged